### ISSUE TITLE
use occ commands to update config file

### ISSUE THREAD

**Issue by r2evans** [sameersbn/docker-nextcloud#2]
... might be a bit more robust and flexible than using `sed`. For instance, it allows dealing correctly with arrays (instead of my *hack* in #1 mandating a user-provided string of a PHP array, pasted unquoted).

This works for `config.php`, not for the `.user.ini` edits. Primary functions I'm thinking would be (using `occ` to really mean `sudo -u www-data php occ`):
- `occ config:system:get memcache.local`
- `occ config:system:set memcache.locking --value=\\OC\\Memcache\\Redis`
- arrays such as `trusted_domains`:
  - `occ config:system:get trusted_domains`
  - `occ config:system:set trusted_domains 0 --value=localhost`
  - `occ config:system:set trusted_domains 1 --value=192.168.0.22`

`occ` also supports data types (e.g., boolean, integer) and `--update-only`.

Eventually, if your docker image ever supports adding specific applications (instead of having to do it manually via the interface), then there is also `config:app:*`.

Reference: https://docs.nextcloud.com/server/9/admin_manual/configuration_server/occ_command.html#config-commands

**Comment by sameersbn** [comment]
Hey @r2evans, sorry for the longest delay., have been a swamped lately. 
Thanks for providing this information. I am replacing the use of the `nextcloud_set_param` and `nextcloud_get_param` with your recommendations.
