### ISSUE TITLE
upgrade to NC11?

### ISSUE THREAD

**Issue by r2evans** [sameersbn/docker-nextcloud#4]
I'm happy to see you updated to 9.0.55 recently, thank you. Do you anticipate upgrading to NC11 anytime soon? To do so, you will need to provide an image for NC10 as well, since (not surprisingly): *"Skipping major releases is not supported"* (from https://docs.nextcloud.com/server/11/admin_manual/maintenance/upgrade.html).

**Comment by r2evans** [comment]
This is great, glad to see the commit. Thanks for maintaining this!

**Comment by sameersbn** [comment]
:+1:
